var group___peripheral__access__layer =
[
    [ "ADC Peripheral Access Layer", "group___a_d_c___peripheral___access___layer.html", "group___a_d_c___peripheral___access___layer" ],
    [ "CMP Peripheral Access Layer", "group___c_m_p___peripheral___access___layer.html", "group___c_m_p___peripheral___access___layer" ],
    [ "DAC Peripheral Access Layer", "group___d_a_c___peripheral___access___layer.html", "group___d_a_c___peripheral___access___layer" ],
    [ "DMA Peripheral Access Layer", "group___d_m_a___peripheral___access___layer.html", "group___d_m_a___peripheral___access___layer" ],
    [ "DMAMUX Peripheral Access Layer", "group___d_m_a_m_u_x___peripheral___access___layer.html", "group___d_m_a_m_u_x___peripheral___access___layer" ],
    [ "FGPIO Peripheral Access Layer", "group___f_g_p_i_o___peripheral___access___layer.html", "group___f_g_p_i_o___peripheral___access___layer" ],
    [ "FTFA Peripheral Access Layer", "group___f_t_f_a___peripheral___access___layer.html", "group___f_t_f_a___peripheral___access___layer" ],
    [ "GPIO Peripheral Access Layer", "group___g_p_i_o___peripheral___access___layer.html", "group___g_p_i_o___peripheral___access___layer" ],
    [ "I2C Peripheral Access Layer", "group___i2_c___peripheral___access___layer.html", "group___i2_c___peripheral___access___layer" ],
    [ "LLWU Peripheral Access Layer", "group___l_l_w_u___peripheral___access___layer.html", "group___l_l_w_u___peripheral___access___layer" ],
    [ "LPTMR Peripheral Access Layer", "group___l_p_t_m_r___peripheral___access___layer.html", "group___l_p_t_m_r___peripheral___access___layer" ],
    [ "MCG Peripheral Access Layer", "group___m_c_g___peripheral___access___layer.html", "group___m_c_g___peripheral___access___layer" ],
    [ "MCM Peripheral Access Layer", "group___m_c_m___peripheral___access___layer.html", "group___m_c_m___peripheral___access___layer" ],
    [ "MTB Peripheral Access Layer", "group___m_t_b___peripheral___access___layer.html", "group___m_t_b___peripheral___access___layer" ],
    [ "MTBDWT Peripheral Access Layer", "group___m_t_b_d_w_t___peripheral___access___layer.html", "group___m_t_b_d_w_t___peripheral___access___layer" ],
    [ "NV Peripheral Access Layer", "group___n_v___peripheral___access___layer.html", "group___n_v___peripheral___access___layer" ],
    [ "OSC Peripheral Access Layer", "group___o_s_c___peripheral___access___layer.html", "group___o_s_c___peripheral___access___layer" ],
    [ "PIT Peripheral Access Layer", "group___p_i_t___peripheral___access___layer.html", "group___p_i_t___peripheral___access___layer" ],
    [ "PMC Peripheral Access Layer", "group___p_m_c___peripheral___access___layer.html", "group___p_m_c___peripheral___access___layer" ],
    [ "PORT Peripheral Access Layer", "group___p_o_r_t___peripheral___access___layer.html", "group___p_o_r_t___peripheral___access___layer" ],
    [ "RCM Peripheral Access Layer", "group___r_c_m___peripheral___access___layer.html", "group___r_c_m___peripheral___access___layer" ],
    [ "ROM Peripheral Access Layer", "group___r_o_m___peripheral___access___layer.html", "group___r_o_m___peripheral___access___layer" ],
    [ "RTC Peripheral Access Layer", "group___r_t_c___peripheral___access___layer.html", "group___r_t_c___peripheral___access___layer" ],
    [ "SIM Peripheral Access Layer", "group___s_i_m___peripheral___access___layer.html", "group___s_i_m___peripheral___access___layer" ],
    [ "SMC Peripheral Access Layer", "group___s_m_c___peripheral___access___layer.html", "group___s_m_c___peripheral___access___layer" ],
    [ "SPI Peripheral Access Layer", "group___s_p_i___peripheral___access___layer.html", "group___s_p_i___peripheral___access___layer" ],
    [ "TPM Peripheral Access Layer", "group___t_p_m___peripheral___access___layer.html", "group___t_p_m___peripheral___access___layer" ],
    [ "TSI Peripheral Access Layer", "group___t_s_i___peripheral___access___layer.html", "group___t_s_i___peripheral___access___layer" ],
    [ "UART Peripheral Access Layer", "group___u_a_r_t___peripheral___access___layer.html", "group___u_a_r_t___peripheral___access___layer" ],
    [ "UARTLP Peripheral Access Layer", "group___u_a_r_t_l_p___peripheral___access___layer.html", "group___u_a_r_t_l_p___peripheral___access___layer" ],
    [ "USB Peripheral Access Layer", "group___u_s_b___peripheral___access___layer.html", "group___u_s_b___peripheral___access___layer" ]
];