var annotated_dup =
[
    [ "mbed", null, [
      [ "detail", null, [
        [ "enable_if", "structmbed_1_1detail_1_1enable__if.html", "structmbed_1_1detail_1_1enable__if" ],
        [ "enable_if< false, R >", "structmbed_1_1detail_1_1enable__if_3_01false_00_01_r_01_4.html", null ],
        [ "is_type", "structmbed_1_1detail_1_1is__type.html", null ],
        [ "nil", "structmbed_1_1detail_1_1nil.html", null ]
      ] ],
      [ "internal", null, [
        [ "is_unsigned", "structmbed_1_1internal_1_1is__unsigned.html", null ],
        [ "is_unsigned< unsigned char >", "structmbed_1_1internal_1_1is__unsigned_3_01unsigned_01char_01_4.html", null ],
        [ "is_unsigned< unsigned int >", "structmbed_1_1internal_1_1is__unsigned_3_01unsigned_01int_01_4.html", null ],
        [ "is_unsigned< unsigned long >", "structmbed_1_1internal_1_1is__unsigned_3_01unsigned_01long_01_4.html", null ],
        [ "is_unsigned< unsigned long long >", "structmbed_1_1internal_1_1is__unsigned_3_01unsigned_01long_01long_01_4.html", null ],
        [ "is_unsigned< unsigned short >", "structmbed_1_1internal_1_1is__unsigned_3_01unsigned_01short_01_4.html", null ]
      ] ],
      [ "span_detail", null, [
        [ "is_convertible", "classmbed_1_1span__detail_1_1is__convertible.html", null ]
      ] ],
      [ "ATCmdParser", "classmbed_1_1_a_t_cmd_parser.html", "classmbed_1_1_a_t_cmd_parser" ],
      [ "BusIn", "classmbed_1_1_bus_in.html", "classmbed_1_1_bus_in" ],
      [ "BusInOut", "classmbed_1_1_bus_in_out.html", "classmbed_1_1_bus_in_out" ],
      [ "BusOut", "classmbed_1_1_bus_out.html", "classmbed_1_1_bus_out" ],
      [ "Callback", "classmbed_1_1_callback.html", null ],
      [ "Callback< R()>", "classmbed_1_1_callback_3_01_r_07_08_4.html", "classmbed_1_1_callback_3_01_r_07_08_4" ],
      [ "Callback< R(A0)>", "classmbed_1_1_callback_3_01_r_07_a0_08_4.html", "classmbed_1_1_callback_3_01_r_07_a0_08_4" ],
      [ "Callback< R(A0, A1)>", "classmbed_1_1_callback_3_01_r_07_a0_00_01_a1_08_4.html", "classmbed_1_1_callback_3_01_r_07_a0_00_01_a1_08_4" ],
      [ "Callback< R(A0, A1, A2)>", "classmbed_1_1_callback_3_01_r_07_a0_00_01_a1_00_01_a2_08_4.html", "classmbed_1_1_callback_3_01_r_07_a0_00_01_a1_00_01_a2_08_4" ],
      [ "Callback< R(A0, A1, A2, A3)>", "classmbed_1_1_callback_3_01_r_07_a0_00_01_a1_00_01_a2_00_01_a3_08_4.html", "classmbed_1_1_callback_3_01_r_07_a0_00_01_a1_00_01_a2_00_01_a3_08_4" ],
      [ "Callback< R(A0, A1, A2, A3, A4)>", "classmbed_1_1_callback_3_01_r_07_a0_00_01_a1_00_01_a2_00_01_a3_00_01_a4_08_4.html", "classmbed_1_1_callback_3_01_r_07_a0_00_01_a1_00_01_a2_00_01_a3_00_01_a4_08_4" ],
      [ "CallChain", "classmbed_1_1_call_chain.html", "classmbed_1_1_call_chain" ],
      [ "CircularBuffer", "classmbed_1_1_circular_buffer.html", "classmbed_1_1_circular_buffer" ],
      [ "CriticalSectionLock", "classmbed_1_1_critical_section_lock.html", "classmbed_1_1_critical_section_lock" ],
      [ "DeepSleepLock", "classmbed_1_1_deep_sleep_lock.html", "classmbed_1_1_deep_sleep_lock" ],
      [ "DigitalIn", "classmbed_1_1_digital_in.html", "classmbed_1_1_digital_in" ],
      [ "DigitalInOut", "classmbed_1_1_digital_in_out.html", "classmbed_1_1_digital_in_out" ],
      [ "DigitalOut", "classmbed_1_1_digital_out.html", "classmbed_1_1_digital_out" ],
      [ "DirHandle", "classmbed_1_1_dir_handle.html", "classmbed_1_1_dir_handle" ],
      [ "FileBase", "classmbed_1_1_file_base.html", "classmbed_1_1_file_base" ],
      [ "FileHandle", "classmbed_1_1_file_handle.html", "classmbed_1_1_file_handle" ],
      [ "FileLike", "classmbed_1_1_file_like.html", "classmbed_1_1_file_like" ],
      [ "FilePath", "classmbed_1_1_file_path.html", "classmbed_1_1_file_path" ],
      [ "FileSystemHandle", "classmbed_1_1_file_system_handle.html", "classmbed_1_1_file_system_handle" ],
      [ "FileSystemLike", "classmbed_1_1_file_system_like.html", "classmbed_1_1_file_system_like" ],
      [ "FunctionPointerArg1", "classmbed_1_1_function_pointer_arg1.html", "classmbed_1_1_function_pointer_arg1" ],
      [ "FunctionPointerArg1< R, void >", "classmbed_1_1_function_pointer_arg1_3_01_r_00_01void_01_4.html", "classmbed_1_1_function_pointer_arg1_3_01_r_00_01void_01_4" ],
      [ "InterruptManager", "classmbed_1_1_interrupt_manager.html", "classmbed_1_1_interrupt_manager" ],
      [ "MbedCRC", "classmbed_1_1_mbed_c_r_c.html", "classmbed_1_1_mbed_c_r_c" ],
      [ "NonCopyable", "classmbed_1_1_non_copyable.html", "classmbed_1_1_non_copyable" ],
      [ "pollfh", "structmbed_1_1pollfh.html", "structmbed_1_1pollfh" ],
      [ "ScopedLock", "classmbed_1_1_scoped_lock.html", "classmbed_1_1_scoped_lock" ],
      [ "ScopedRamExecutionLock", "classmbed_1_1_scoped_ram_execution_lock.html", "classmbed_1_1_scoped_ram_execution_lock" ],
      [ "ScopedRomWriteLock", "classmbed_1_1_scoped_rom_write_lock.html", "classmbed_1_1_scoped_rom_write_lock" ],
      [ "SharedPtr", "classmbed_1_1_shared_ptr.html", "classmbed_1_1_shared_ptr" ],
      [ "Span", "structmbed_1_1_span.html", "structmbed_1_1_span" ],
      [ "Span< ElementType, SPAN_DYNAMIC_EXTENT >", "structmbed_1_1_span_3_01_element_type_00_01_s_p_a_n___d_y_n_a_m_i_c___e_x_t_e_n_t_01_4.html", "structmbed_1_1_span_3_01_element_type_00_01_s_p_a_n___d_y_n_a_m_i_c___e_x_t_e_n_t_01_4" ],
      [ "Stream", "classmbed_1_1_stream.html", "classmbed_1_1_stream" ],
      [ "Ticker", "classmbed_1_1_ticker.html", "classmbed_1_1_ticker" ],
      [ "Timeout", "classmbed_1_1_timeout.html", "classmbed_1_1_timeout" ],
      [ "Timer", "classmbed_1_1_timer.html", "classmbed_1_1_timer" ],
      [ "TimerEvent", "classmbed_1_1_timer_event.html", "classmbed_1_1_timer_event" ],
      [ "Transaction", "classmbed_1_1_transaction.html", "classmbed_1_1_transaction" ],
      [ "transaction_t", "structmbed_1_1transaction__t.html", "structmbed_1_1transaction__t" ]
    ] ],
    [ "__iar_u32", "struct____iar__u32.html", "struct____iar__u32" ],
    [ "_ARM_DRIVER_STORAGE", "struct___a_r_m___d_r_i_v_e_r___s_t_o_r_a_g_e.html", "struct___a_r_m___d_r_i_v_e_r___s_t_o_r_a_g_e" ],
    [ "_ARM_DRIVER_VERSION", "struct___a_r_m___d_r_i_v_e_r___v_e_r_s_i_o_n.html", "struct___a_r_m___d_r_i_v_e_r___v_e_r_s_i_o_n" ],
    [ "_ARM_STORAGE_BLOCK", "struct___a_r_m___s_t_o_r_a_g_e___b_l_o_c_k.html", "struct___a_r_m___s_t_o_r_a_g_e___b_l_o_c_k" ],
    [ "_ARM_STORAGE_BLOCK_ATTRIBUTES", "struct___a_r_m___s_t_o_r_a_g_e___b_l_o_c_k___a_t_t_r_i_b_u_t_e_s.html", "struct___a_r_m___s_t_o_r_a_g_e___b_l_o_c_k___a_t_t_r_i_b_u_t_e_s" ],
    [ "_ARM_STORAGE_CAPABILITIES", "struct___a_r_m___s_t_o_r_a_g_e___c_a_p_a_b_i_l_i_t_i_e_s.html", "struct___a_r_m___s_t_o_r_a_g_e___c_a_p_a_b_i_l_i_t_i_e_s" ],
    [ "_ARM_STORAGE_INFO", "struct___a_r_m___s_t_o_r_a_g_e___i_n_f_o.html", "struct___a_r_m___s_t_o_r_a_g_e___i_n_f_o" ],
    [ "_ARM_STORAGE_SECURITY_FEATURES", "struct___a_r_m___s_t_o_r_a_g_e___s_e_c_u_r_i_t_y___f_e_a_t_u_r_e_s.html", "struct___a_r_m___s_t_o_r_a_g_e___s_e_c_u_r_i_t_y___f_e_a_t_u_r_e_s" ],
    [ "_ARM_STORAGE_STATUS", "struct___a_r_m___s_t_o_r_a_g_e___s_t_a_t_u_s.html", "struct___a_r_m___s_t_o_r_a_g_e___s_t_a_t_u_s" ],
    [ "_mbed_error_ctx", "struct__mbed__error__ctx.html", "struct__mbed__error__ctx" ],
    [ "ADC_Type", "struct_a_d_c___type.html", "struct_a_d_c___type" ],
    [ "analogin_s", "structanalogin__s.html", "structanalogin__s" ],
    [ "APSR_Type", "union_a_p_s_r___type.html", "union_a_p_s_r___type" ],
    [ "args_t", "structargs__t.html", "structargs__t" ],
    [ "arm_bilinear_interp_instance_f32", "structarm__bilinear__interp__instance__f32.html", "structarm__bilinear__interp__instance__f32" ],
    [ "arm_bilinear_interp_instance_q15", "structarm__bilinear__interp__instance__q15.html", "structarm__bilinear__interp__instance__q15" ],
    [ "arm_bilinear_interp_instance_q31", "structarm__bilinear__interp__instance__q31.html", "structarm__bilinear__interp__instance__q31" ],
    [ "arm_bilinear_interp_instance_q7", "structarm__bilinear__interp__instance__q7.html", "structarm__bilinear__interp__instance__q7" ],
    [ "arm_biquad_cas_df1_32x64_ins_q31", "structarm__biquad__cas__df1__32x64__ins__q31.html", "structarm__biquad__cas__df1__32x64__ins__q31" ],
    [ "arm_biquad_cascade_df2T_instance_f32", "structarm__biquad__cascade__df2_t__instance__f32.html", "structarm__biquad__cascade__df2_t__instance__f32" ],
    [ "arm_biquad_cascade_df2T_instance_f64", "structarm__biquad__cascade__df2_t__instance__f64.html", "structarm__biquad__cascade__df2_t__instance__f64" ],
    [ "arm_biquad_cascade_stereo_df2T_instance_f32", "structarm__biquad__cascade__stereo__df2_t__instance__f32.html", "structarm__biquad__cascade__stereo__df2_t__instance__f32" ],
    [ "arm_biquad_casd_df1_inst_f32", "structarm__biquad__casd__df1__inst__f32.html", "structarm__biquad__casd__df1__inst__f32" ],
    [ "arm_biquad_casd_df1_inst_q15", "structarm__biquad__casd__df1__inst__q15.html", "structarm__biquad__casd__df1__inst__q15" ],
    [ "arm_biquad_casd_df1_inst_q31", "structarm__biquad__casd__df1__inst__q31.html", "structarm__biquad__casd__df1__inst__q31" ],
    [ "arm_cfft_instance_f32", "structarm__cfft__instance__f32.html", "structarm__cfft__instance__f32" ],
    [ "arm_cfft_instance_q15", "structarm__cfft__instance__q15.html", "structarm__cfft__instance__q15" ],
    [ "arm_cfft_instance_q31", "structarm__cfft__instance__q31.html", "structarm__cfft__instance__q31" ],
    [ "arm_cfft_radix2_instance_f32", "structarm__cfft__radix2__instance__f32.html", "structarm__cfft__radix2__instance__f32" ],
    [ "arm_cfft_radix2_instance_q15", "structarm__cfft__radix2__instance__q15.html", "structarm__cfft__radix2__instance__q15" ],
    [ "arm_cfft_radix2_instance_q31", "structarm__cfft__radix2__instance__q31.html", "structarm__cfft__radix2__instance__q31" ],
    [ "arm_cfft_radix4_instance_f32", "structarm__cfft__radix4__instance__f32.html", "structarm__cfft__radix4__instance__f32" ],
    [ "arm_cfft_radix4_instance_q15", "structarm__cfft__radix4__instance__q15.html", "structarm__cfft__radix4__instance__q15" ],
    [ "arm_cfft_radix4_instance_q31", "structarm__cfft__radix4__instance__q31.html", "structarm__cfft__radix4__instance__q31" ],
    [ "arm_dct4_instance_f32", "structarm__dct4__instance__f32.html", "structarm__dct4__instance__f32" ],
    [ "arm_dct4_instance_q15", "structarm__dct4__instance__q15.html", "structarm__dct4__instance__q15" ],
    [ "arm_dct4_instance_q31", "structarm__dct4__instance__q31.html", "structarm__dct4__instance__q31" ],
    [ "arm_fir_decimate_instance_f32", "structarm__fir__decimate__instance__f32.html", "structarm__fir__decimate__instance__f32" ],
    [ "arm_fir_decimate_instance_q15", "structarm__fir__decimate__instance__q15.html", "structarm__fir__decimate__instance__q15" ],
    [ "arm_fir_decimate_instance_q31", "structarm__fir__decimate__instance__q31.html", "structarm__fir__decimate__instance__q31" ],
    [ "arm_fir_instance_f32", "structarm__fir__instance__f32.html", "structarm__fir__instance__f32" ],
    [ "arm_fir_instance_q15", "structarm__fir__instance__q15.html", "structarm__fir__instance__q15" ],
    [ "arm_fir_instance_q31", "structarm__fir__instance__q31.html", "structarm__fir__instance__q31" ],
    [ "arm_fir_instance_q7", "structarm__fir__instance__q7.html", "structarm__fir__instance__q7" ],
    [ "arm_fir_interpolate_instance_f32", "structarm__fir__interpolate__instance__f32.html", "structarm__fir__interpolate__instance__f32" ],
    [ "arm_fir_interpolate_instance_q15", "structarm__fir__interpolate__instance__q15.html", "structarm__fir__interpolate__instance__q15" ],
    [ "arm_fir_interpolate_instance_q31", "structarm__fir__interpolate__instance__q31.html", "structarm__fir__interpolate__instance__q31" ],
    [ "arm_fir_lattice_instance_f32", "structarm__fir__lattice__instance__f32.html", "structarm__fir__lattice__instance__f32" ],
    [ "arm_fir_lattice_instance_q15", "structarm__fir__lattice__instance__q15.html", "structarm__fir__lattice__instance__q15" ],
    [ "arm_fir_lattice_instance_q31", "structarm__fir__lattice__instance__q31.html", "structarm__fir__lattice__instance__q31" ],
    [ "arm_fir_sparse_instance_f32", "structarm__fir__sparse__instance__f32.html", "structarm__fir__sparse__instance__f32" ],
    [ "arm_fir_sparse_instance_q15", "structarm__fir__sparse__instance__q15.html", "structarm__fir__sparse__instance__q15" ],
    [ "arm_fir_sparse_instance_q31", "structarm__fir__sparse__instance__q31.html", "structarm__fir__sparse__instance__q31" ],
    [ "arm_fir_sparse_instance_q7", "structarm__fir__sparse__instance__q7.html", "structarm__fir__sparse__instance__q7" ],
    [ "arm_iir_lattice_instance_f32", "structarm__iir__lattice__instance__f32.html", "structarm__iir__lattice__instance__f32" ],
    [ "arm_iir_lattice_instance_q15", "structarm__iir__lattice__instance__q15.html", "structarm__iir__lattice__instance__q15" ],
    [ "arm_iir_lattice_instance_q31", "structarm__iir__lattice__instance__q31.html", "structarm__iir__lattice__instance__q31" ],
    [ "arm_linear_interp_instance_f32", "structarm__linear__interp__instance__f32.html", "structarm__linear__interp__instance__f32" ],
    [ "arm_lms_instance_f32", "structarm__lms__instance__f32.html", "structarm__lms__instance__f32" ],
    [ "arm_lms_instance_q15", "structarm__lms__instance__q15.html", "structarm__lms__instance__q15" ],
    [ "arm_lms_instance_q31", "structarm__lms__instance__q31.html", "structarm__lms__instance__q31" ],
    [ "arm_lms_norm_instance_f32", "structarm__lms__norm__instance__f32.html", "structarm__lms__norm__instance__f32" ],
    [ "arm_lms_norm_instance_q15", "structarm__lms__norm__instance__q15.html", "structarm__lms__norm__instance__q15" ],
    [ "arm_lms_norm_instance_q31", "structarm__lms__norm__instance__q31.html", "structarm__lms__norm__instance__q31" ],
    [ "arm_matrix_instance_f32", "structarm__matrix__instance__f32.html", "structarm__matrix__instance__f32" ],
    [ "arm_matrix_instance_f64", "structarm__matrix__instance__f64.html", "structarm__matrix__instance__f64" ],
    [ "arm_matrix_instance_q15", "structarm__matrix__instance__q15.html", "structarm__matrix__instance__q15" ],
    [ "arm_matrix_instance_q31", "structarm__matrix__instance__q31.html", "structarm__matrix__instance__q31" ],
    [ "ARM_MPU_Region_t", "struct_a_r_m___m_p_u___region__t.html", "struct_a_r_m___m_p_u___region__t" ],
    [ "arm_pid_instance_f32", "structarm__pid__instance__f32.html", "structarm__pid__instance__f32" ],
    [ "arm_pid_instance_q15", "structarm__pid__instance__q15.html", "structarm__pid__instance__q15" ],
    [ "arm_pid_instance_q31", "structarm__pid__instance__q31.html", "structarm__pid__instance__q31" ],
    [ "arm_rfft_fast_instance_f32", "structarm__rfft__fast__instance__f32.html", "structarm__rfft__fast__instance__f32" ],
    [ "arm_rfft_instance_f32", "structarm__rfft__instance__f32.html", "structarm__rfft__instance__f32" ],
    [ "arm_rfft_instance_q15", "structarm__rfft__instance__q15.html", "structarm__rfft__instance__q15" ],
    [ "arm_rfft_instance_q31", "structarm__rfft__instance__q31.html", "structarm__rfft__instance__q31" ],
    [ "buffer_s", "structbuffer__s.html", "structbuffer__s" ],
    [ "CMP_Type", "struct_c_m_p___type.html", "struct_c_m_p___type" ],
    [ "CONTROL_Type", "union_c_o_n_t_r_o_l___type.html", "union_c_o_n_t_r_o_l___type" ],
    [ "core_util_atomic_flag", "structcore__util__atomic__flag.html", "structcore__util__atomic__flag" ],
    [ "CoreDebug_Type", "struct_core_debug___type.html", "struct_core_debug___type" ],
    [ "crc_mbed_config", "structcrc__mbed__config.html", "structcrc__mbed__config" ],
    [ "CThunk", "class_c_thunk.html", "class_c_thunk" ],
    [ "CThunkBase", "class_c_thunk_base.html", "class_c_thunk_base" ],
    [ "dac_s", "structdac__s.html", "structdac__s" ],
    [ "DAC_Type", "struct_d_a_c___type.html", "struct_d_a_c___type" ],
    [ "dirent", "structdirent.html", "structdirent" ],
    [ "DMA_Type", "struct_d_m_a___type.html", "struct_d_m_a___type" ],
    [ "DMAMUX_Type", "struct_d_m_a_m_u_x___type.html", "struct_d_m_a_m_u_x___type" ],
    [ "DWT_Type", "struct_d_w_t___type.html", "struct_d_w_t___type" ],
    [ "FGPIO_Type", "struct_f_g_p_i_o___type.html", "struct_f_g_p_i_o___type" ],
    [ "flash_algo_t", "structflash__algo__t.html", "structflash__algo__t" ],
    [ "flash_s", "structflash__s.html", "structflash__s" ],
    [ "flash_target_config_t", "structflash__target__config__t.html", "structflash__target__config__t" ],
    [ "FPU_Type", "struct_f_p_u___type.html", "struct_f_p_u___type" ],
    [ "FTFA_Type", "struct_f_t_f_a___type.html", "struct_f_t_f_a___type" ],
    [ "gpio_irq_s", "structgpio__irq__s.html", "structgpio__irq__s" ],
    [ "gpio_t", "structgpio__t.html", "structgpio__t" ],
    [ "GPIO_Type", "struct_g_p_i_o___type.html", "struct_g_p_i_o___type" ],
    [ "i2c_s", "structi2c__s.html", "structi2c__s" ],
    [ "I2C_Type", "struct_i2_c___type.html", "struct_i2_c___type" ],
    [ "IPSR_Type", "union_i_p_s_r___type.html", "union_i_p_s_r___type" ],
    [ "ITM_Type", "struct_i_t_m___type.html", "struct_i_t_m___type" ],
    [ "LLWU_Type", "struct_l_l_w_u___type.html", "struct_l_l_w_u___type" ],
    [ "LowPowerTickerWrapper", "class_low_power_ticker_wrapper.html", "class_low_power_ticker_wrapper" ],
    [ "LPTMR_Type", "struct_l_p_t_m_r___type.html", "struct_l_p_t_m_r___type" ],
    [ "mbed_fault_context_t", "structmbed__fault__context__t.html", "structmbed__fault__context__t" ],
    [ "mbed_stats_cpu_t", "structmbed__stats__cpu__t.html", "structmbed__stats__cpu__t" ],
    [ "mbed_stats_heap_t", "structmbed__stats__heap__t.html", "structmbed__stats__heap__t" ],
    [ "mbed_stats_stack_t", "structmbed__stats__stack__t.html", "structmbed__stats__stack__t" ],
    [ "mbed_stats_sys_t", "structmbed__stats__sys__t.html", "structmbed__stats__sys__t" ],
    [ "mbed_stats_thread_t", "structmbed__stats__thread__t.html", "structmbed__stats__thread__t" ],
    [ "MCG_Type", "struct_m_c_g___type.html", "struct_m_c_g___type" ],
    [ "MCM_Type", "struct_m_c_m___type.html", "struct_m_c_m___type" ],
    [ "MMA8451Q", "class_m_m_a8451_q.html", "class_m_m_a8451_q" ],
    [ "MTB_Type", "struct_m_t_b___type.html", "struct_m_t_b___type" ],
    [ "MTBDWT_Type", "struct_m_t_b_d_w_t___type.html", "struct_m_t_b_d_w_t___type" ],
    [ "NV_Type", "struct_n_v___type.html", "struct_n_v___type" ],
    [ "NVIC_Type", "struct_n_v_i_c___type.html", "struct_n_v_i_c___type" ],
    [ "OSC_Type", "struct_o_s_c___type.html", "struct_o_s_c___type" ],
    [ "PinMap", "struct_pin_map.html", "struct_pin_map" ],
    [ "PIT_Type", "struct_p_i_t___type.html", "struct_p_i_t___type" ],
    [ "PlatformMutex", "class_platform_mutex.html", "class_platform_mutex" ],
    [ "PMC_Type", "struct_p_m_c___type.html", "struct_p_m_c___type" ],
    [ "pollfd", "structpollfd.html", "structpollfd" ],
    [ "port_s", "structport__s.html", "structport__s" ],
    [ "PORT_Type", "struct_p_o_r_t___type.html", "struct_p_o_r_t___type" ],
    [ "pwmout_s", "structpwmout__s.html", "structpwmout__s" ],
    [ "RCM_Type", "struct_r_c_m___type.html", "struct_r_c_m___type" ],
    [ "ROM_Type", "struct_r_o_m___type.html", "struct_r_o_m___type" ],
    [ "RTC_Type", "struct_r_t_c___type.html", "struct_r_t_c___type" ],
    [ "SCB_Type", "struct_s_c_b___type.html", "struct_s_c_b___type" ],
    [ "SCnSCB_Type", "struct_s_cn_s_c_b___type.html", "struct_s_cn_s_c_b___type" ],
    [ "sector_info_t", "structsector__info__t.html", "structsector__info__t" ],
    [ "serial_s", "structserial__s.html", "structserial__s" ],
    [ "SIM_Type", "struct_s_i_m___type.html", "struct_s_i_m___type" ],
    [ "SingletonPtr", "struct_singleton_ptr.html", "struct_singleton_ptr" ],
    [ "SMC_Type", "struct_s_m_c___type.html", "struct_s_m_c___type" ],
    [ "spi_s", "structspi__s.html", "structspi__s" ],
    [ "SPI_Type", "struct_s_p_i___type.html", "struct_s_p_i___type" ],
    [ "stat", "structstat.html", "structstat" ],
    [ "statvfs", "structstatvfs.html", "structstatvfs" ],
    [ "SysTick_Type", "struct_sys_tick___type.html", "struct_sys_tick___type" ],
    [ "ticker_data_t", "structticker__data__t.html", "structticker__data__t" ],
    [ "ticker_event_queue_t", "structticker__event__queue__t.html", "structticker__event__queue__t" ],
    [ "ticker_event_s", "structticker__event__s.html", "structticker__event__s" ],
    [ "ticker_info_t", "structticker__info__t.html", "structticker__info__t" ],
    [ "ticker_interface_t", "structticker__interface__t.html", "structticker__interface__t" ],
    [ "TPI_Type", "struct_t_p_i___type.html", "struct_t_p_i___type" ],
    [ "TPM_Type", "struct_t_p_m___type.html", "struct_t_p_m___type" ],
    [ "TSI_Type", "struct_t_s_i___type.html", "struct_t_s_i___type" ],
    [ "TSISensor", "class_t_s_i_sensor.html", "class_t_s_i_sensor" ],
    [ "UART_Type", "struct_u_a_r_t___type.html", "struct_u_a_r_t___type" ],
    [ "UARTLP_Type", "struct_u_a_r_t_l_p___type.html", "struct_u_a_r_t_l_p___type" ],
    [ "USB_Type", "struct_u_s_b___type.html", "struct_u_s_b___type" ],
    [ "xPSR_Type", "unionx_p_s_r___type.html", "unionx_p_s_r___type" ]
];