var group__platform =
[
    [ "ATCmdParser class", "group__platform___a_t_cmd_parser.html", "group__platform___a_t_cmd_parser" ],
    [ "Callback class", "group__platform___callback.html", "group__platform___callback" ],
    [ "CallChain class", "group__platform___call_chain.html", "group__platform___call_chain" ],
    [ "CircularBuffer functions", "group__platform___circular_buffer.html", "group__platform___circular_buffer" ],
    [ "CriticalSectionLock functions", "group__platform___critical_section_lock.html", "group__platform___critical_section_lock" ],
    [ "CThunk class", "group__platform___c_thunk.html", "group__platform___c_thunk" ],
    [ "DeepSleepLock functions", "group__platform___deep_sleep_lock.html", "group__platform___deep_sleep_lock" ],
    [ "DirHandle functions", "group__platform___dir_handle.html", "group__platform___dir_handle" ],
    [ "FileBase class", "group__platform___file_base.html", "group__platform___file_base" ],
    [ "FileHandle functions", "group__platform___file_handle.html", "group__platform___file_handle" ],
    [ "FileLike class", "group__platform___file_like.html", "group__platform___file_like" ],
    [ "FilePath class", "group__platform___file_path.html", "group__platform___file_path" ],
    [ "FileSystemHandle functions", "group__platform___file_system_handle.html", "group__platform___file_system_handle" ],
    [ "FileSystemLike functions", "group__platform___file_system_like.html", "group__platform___file_system_like" ],
    [ "FunctionPointer class", "group__platform___function_pointer.html", "group__platform___function_pointer" ],
    [ "Assert macros", "group__platform___assert.html", "group__platform___assert" ],
    [ "critical section function", "group__platform__critical.html", "group__platform__critical" ],
    [ "Debug functions", "group__platform__debug.html", null ],
    [ "Error functions", "group__platform__error.html", "group__platform__error" ],
    [ "Network interface and other utility functions", "group__platform__interface.html", "group__platform__interface" ],
    [ "mem_trace functions", "group__platform__mem__trace.html", "group__platform__mem__trace" ],
    [ "mktime functions", "group__platform__mktime.html", "group__platform__mktime" ],
    [ "MPU management functions", "group__platform__mpu__mgmt.html", null ],
    [ "poll functions", "group__platform__poll.html", "group__platform__poll" ],
    [ "Power management functions", "group__platform__power__mgmt.html", "group__platform__power__mgmt" ],
    [ "preprocessor macros", "group__platform__preprocessor.html", "group__platform__preprocessor" ],
    [ "Retarget functions", "group__platform__retarget.html", "group__platform__retarget" ],
    [ "rtc_time functions", "group__platform__rtc__time.html", "group__platform__rtc__time" ],
    [ "stats functions", "group__platform__stats.html", "group__platform__stats" ],
    [ "Toolchain functions", "group__platform__toolchain.html", "group__platform__toolchain" ],
    [ "Version macros", "group__platform__version.html", "group__platform__version" ],
    [ "wait_api functions", "group__platform__wait__api.html", "group__platform__wait__api" ],
    [ "NonCopyable class", "group__platform___non_copyable.html", "group__platform___non_copyable" ],
    [ "PlatformMutex class", "group__platform___platform_mutex.html", "group__platform___platform_mutex" ],
    [ "ScopedLock functions", "group__platform___scoped_lock.html", "group__platform___scoped_lock" ],
    [ "SingletonPtr class", "group__platform___singleton_ptr.html", "group__platform___singleton_ptr" ],
    [ "Span class", "group__platform___span.html", "group__platform___span" ],
    [ "Stream class", "group__platform___stream.html", "group__platform___stream" ],
    [ "Transaction class", "group__platform___transaction.html", "group__platform___transaction" ],
    [ "ScopedRamExecutionLock", "classmbed_1_1_scoped_ram_execution_lock.html", [
      [ "ScopedRamExecutionLock", "classmbed_1_1_scoped_ram_execution_lock.html#a5cd3c14385327242abb4865395b03261", null ],
      [ "~ScopedRamExecutionLock", "classmbed_1_1_scoped_ram_execution_lock.html#ad64e6a4648f5c69fb2ec0f37bb0b1db2", null ]
    ] ],
    [ "ScopedRomWriteLock", "classmbed_1_1_scoped_rom_write_lock.html", [
      [ "ScopedRomWriteLock", "classmbed_1_1_scoped_rom_write_lock.html#ae98d6070b6b3a6ccfcdfa0cfe4402477", null ],
      [ "~ScopedRomWriteLock", "classmbed_1_1_scoped_rom_write_lock.html#af224f6d4729ecc3aa9711c7a71307bf1", null ],
      [ "MBED_MEM_TRACE_MALLOC", "group__platform.html#ggabed82baf7f470b522273a3e37c24c600a752b09a904f26d7ca96aea9a702c1b9c", null ],
      [ "MBED_MEM_TRACE_REALLOC", "group__platform.html#ggabed82baf7f470b522273a3e37c24c600a2d1887430366cb21bb28877ca31bc529", null ],
      [ "MBED_MEM_TRACE_CALLOC", "group__platform.html#ggabed82baf7f470b522273a3e37c24c600ac413292d3d32425ae3e95bcd92c8f38c", null ],
      [ "MBED_MEM_TRACE_FREE", "group__platform.html#ggabed82baf7f470b522273a3e37c24c600a96eb0b60b29a4878ce7499a367ccbd92", null ]
    ] ]
];